version: "3.3"
services:
    app-backend:
        build: ../server
        image: admin-app
        container_name: backend
        restart: always
        ports:
            - 8082:8082
    app-frontend:
            build: ../public/
            image: admin-app
            container_name: frontend
            restart: always
            ports:
                - 4200:4200
            expose:
                - "4200"